//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uploadimage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Image
    {
        [Key,Required(ErrorMessage ="El campo id es requerido"),Display(Name ="Id de imagen")]
        public int ImageId { get; set; }

        [Display(Name ="Titulo"),Required(ErrorMessage ="El campo {0} titulo es requerido")]
        public string Title { get; set; }
        
        [Display(Name ="Imagen"),Required(ErrorMessage ="La imagen es requerida")]
        public string ImagePath { get; set; }

        [Required(ErrorMessage ="El {0} es requerido")]
        public int ProducId { get; set; }

        //[FileExtensions(Extensions = "jpg,jpeg,gif,png", ErrorMessage = "Extencion no valida")]
        public HttpPostedFileBase ImageFile { get; set; }
        /*
         *Actúa como clase base para las clases que proporcionan acceso a los archivos individuales cargados por un cliente.
         * Esta clase nos da acceso no sólo al contenido del fichero subido, sinó a más información (su content-type, su tamaño, 
         * el path completo desde donde se ha subido,…).
        */

        public virtual Product Product { get; set; }
    }
}
